### ISSUE TITLE
Get Single Post

### ISSUE THREAD

**Issue by ctucker0113** [ctucker0113/RarePublishing#5]

**Comment by PaulPatterson48** [comment]
Given: As a user I want to pull a single post by id. This would require the following: 
id  int IDENTITY(1,1)  primary key
user_id int foreign key
category_id int 
title varchar(50)
publication_date datetime
image_url varchar(255)
content varchar(255)
approved bit -- boolean

Developer: 
Program.cs:
List<Post> post = new List<Post>
{
    new Post() {Id=0, UserId=0, CategoryId=0, Title="How the Wind Blows", PublicationDate="05/25/1990", ImageUrl="http://www.google.com, Content="This is my content", Approved=false"}
};

endpoint
app.MapGet("/api/post/{id}", (int id) =>
{
    Post post = posts.FirstOrDefault(p => p.Id == id);
     if(post == null)
     {
            return Results.NotFound();
      }
       return Results.Ok(post)
});

Create Models (DTO)
using System
namespace RarePublishingAPI.Models
{
     public class Post
      {
           public int Id { get; set; }
           public  int UserId {get; set: }
           public int CategoryId {get; set:}
            public string Title {get; set:}
            public string PublicationDate {get; set:}
            public string ImageUrl {get; set;}
            public string Content {get; set; }
             public bool Approved {get; set;}
           }
  }
