### ISSUE TITLE
Get all Comments on a Single Post

### ISSUE THREAD

**Issue by ctucker0113** [ctucker0113/RarePublishing#6]

**Comment by PaulPatterson48** [comment]
Acceptance Criteria
Given: A Post can have many Comments you want to be able to pull all comments related to a Post
id int IDENTITY(1,1)  not null primary key
author_id int 
post_id int
content varchar(255) --text

Dev Notes: 
Program.cs will contain a list of comments for the posts
`List<Comments> comments = new<Comments>
{
     new Comments() {Id=0, AuthorId=0, PostId=0, Content="This is my Content"
} `
`app.MapGet("/api/posts/{postId}/comments", =>
{
        if( postId = null)
         {
               return Results.BadRequest();
         }
          if (int.TryPase(postId?.ToString(), out var postId))
          {
          var post = posts.FirsOrDefault(p => p.id == postId);
           }
           return post.Comments;
}`
